In [1]:
# Import the neccessary datasets
import pandas as pd
import numpy as np

### Load the datasets

In [2]:
# Load the datasets
train = pd.read_csv('Data/train.csv')
test = pd.read_csv('Data/test.csv')
sample = pd.read_csv('Data/sample_submission2.csv')
sample.EmployeeNo = test.EmployeeNo

### Explore the Data

In [3]:
# check out the shape, head and info of the data
print("Shape of train data is ", train.shape, " and shape of test data is ", test.shape)

Shape of train data is  (38312, 19)  and shape of test data is  (16496, 18)

In [4]:
columns = ['EmployeeNo', 'Division', 'Qualification', 'Gender',
       'Channel_of_Recruitment', 'Trainings_Attended', 'Year_of_birth',
       'Last_performance_score', 'Year_of_recruitment', 'Targets_met',
       'Previous_Award', 'Training_score_average', 'State_Of_Origin',
       'Foreign_schooled', 'Marital_Status', 'Past_Disciplinary_Action',
       'Previous_IntraDepartmental_Movement', 'No_of_previous_employers',
       'Promoted_or_Not']

In [5]:
# Check the head of the training data
train.head()

,EmployeeNo,Division,Qualification,Gender,Channel_of_Recruitment,Trainings_Attended,Year_of_birth,Last_performance_score,Year_of_recruitment,Targets_met,Previous_Award,Training_score_average,State_Of_Origin,Foreign_schooled,Marital_Status,Past_Disciplinary_Action,Previous_IntraDepartmental_Movement,No_of_previous_employers,Promoted_or_Not
0,YAK/S/00001,Commercial Sales and Marketing,"MSc, MBA and PhD",Female,Direct Internal process,2,1986,12.5,2011,1,0,41,ANAMBRA,No,Married,No,No,0,0
1,YAK/S/00002,Customer Support and Field Operations,First Degree or HND,Male,Agency and others,2,1991,12.5,2015,0,0,52,ANAMBRA,Yes,Married,No,No,0,0
2,YAK/S/00003,Commercial Sales and Marketing,First Degree or HND,Male,Direct Internal process,2,1987,7.5,2012,0,0,42,KATSINA,Yes,Married,No,No,0,0
3,YAK/S/00004,Commercial Sales and Marketing,First Degree or HND,Male,Agency and others,3,1982,2.5,2009,0,0,42,NIGER,Yes,Single,No,No,1,0
4,YAK/S/00006,Information and Strategy,First Degree or HND,Male,Direct Internal process,3,1990,7.5,2012,0,0,77,AKWA IBOM,Yes,Married,No,No,1,0

In [6]:
# Check the head of the testing data
test.head()

,EmployeeNo,Division,Qualification,Gender,Channel_of_Recruitment,Trainings_Attended,Year_of_birth,Last_performance_score,Year_of_recruitment,Targets_met,Previous_Award,Training_score_average,State_Of_Origin,Foreign_schooled,Marital_Status,Past_Disciplinary_Action,Previous_IntraDepartmental_Movement,No_of_previous_employers
0,YAK/S/00005,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1976,7.5,2017,0,0,65,FCT,Yes,Married,No,No,1
1,YAK/S/00011,Information Technology and Solution Support,NaN,Male,Direct Internal process,2,1991,0.0,2018,0,0,69,OGUN,Yes,Married,No,No,1
2,YAK/S/00015,Research and Innovation,"MSc, MBA and PhD",Male,Direct Internal process,2,1984,7.5,2012,0,0,76,KANO,Yes,Married,No,No,1
3,YAK/S/00016,Customer Support and Field Operations,First Degree or HND,Male,Agency and others,2,1984,2.5,2009,0,0,52,RIVERS,No,Single,No,No,1
4,YAK/S/00017,Information Technology and Solution Support,First Degree or HND,Male,Agency and others,2,1983,7.5,2014,1,0,69,FCT,Yes,Married,No,No,0

In [7]:
print("Information of the training data", "\n\n", train.info())
print("Information of the testing data", "\n\n", test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38312 entries, 0 to 38311
Data columns (total 19 columns):
EmployeeNo                             38312 non-null object
Division                               38312 non-null object
Qualification                          36633 non-null object
Gender                                 38312 non-null object
Channel_of_Recruitment                 38312 non-null object
Trainings_Attended                     38312 non-null int64
Year_of_birth                          38312 non-null int64
Last_performance_score                 38312 non-null float64
Year_of_recruitment                    38312 non-null int64
Targets_met                            38312 non-null int64
Previous_Award                         38312 non-null int64
Training_score_average                 38312 non-null int64
State_Of_Origin                        38312 non-null object
Foreign_schooled                       38312 non-null object
Marital_Status                         38312 non-null object
Past_Disciplinary_Action               38312 non-null object
Previous_IntraDepartmental_Movement    38312 non-null object
No_of_previous_employers               38312 non-null object
Promoted_or_Not                        38312 non-null int64
dtypes: float64(1), int64(7), object(11)
memory usage: 5.6+ MB
Information of the training data

 None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16496 entries, 0 to 16495
Data columns (total 18 columns):
EmployeeNo                             16496 non-null object
Division                               16496 non-null object
Qualification                          15766 non-null object
Gender                                 16496 non-null object
Channel_of_Recruitment                 16496 non-null object
Trainings_Attended                     16496 non-null int64
Year_of_birth                          16496 non-null int64
Last_performance_score                 16496 non-null float64
Year_of_recruitment                    16496 non-null int64
Targets_met                            16496 non-null int64
Previous_Award                         16496 non-null int64
Training_score_average                 16496 non-null int64
State_Of_Origin                        16496 non-null object
Foreign_schooled                       16496 non-null object
Marital_Status                         16496 non-null object
Past_Disciplinary_Action               16496 non-null object
Previous_IntraDepartmental_Movement    16496 non-null object
No_of_previous_employers               16496 non-null object
dtypes: float64(1), int64(6), object(11)
memory usage: 2.3+ MB
Information of the testing data

 None

### Data Wrangling

In [8]:
# Check for missing values in training and testing data
print("Missing values in train data","\n",train.isnull().sum())
print("Missing values in test data","\n", test.isnull().sum())

Missing values in train data
 EmployeeNo                                0
Division                                  0
Qualification                          1679
Gender                                    0
Channel_of_Recruitment                    0
Trainings_Attended                        0
Year_of_birth                             0
Last_performance_score                    0
Year_of_recruitment                       0
Targets_met                               0
Previous_Award                            0
Training_score_average                    0
State_Of_Origin                           0
Foreign_schooled                          0
Marital_Status                            0
Past_Disciplinary_Action                  0
Previous_IntraDepartmental_Movement       0
No_of_previous_employers                  0
Promoted_or_Not                           0
dtype: int64
Missing values in test data
 EmployeeNo                               0
Division                                 0
Qualification                          730
Gender                                   0
Channel_of_Recruitment                   0
Trainings_Attended                       0
Year_of_birth                            0
Last_performance_score                   0
Year_of_recruitment                      0
Targets_met                              0
Previous_Award                           0
Training_score_average                   0
State_Of_Origin                          0
Foreign_schooled                         0
Marital_Status                           0
Past_Disciplinary_Action                 0
Previous_IntraDepartmental_Movement      0
No_of_previous_employers                 0
dtype: int64

In [9]:
# Take care of the missing values by filling them up with the most frequent value
print("For train \n ", train.Qualification.value_counts())
print("For test \n", test.Qualification.value_counts())

train.fillna("First Degree or HND", inplace=True)
test.fillna("First Degree or HND", inplace=True)

For train
  First Degree or HND         25578
MSc, MBA and PhD            10469
Non-University Education      586
Name: Qualification, dtype: int64
For test
 First Degree or HND         11091
MSc, MBA and PhD             4456
Non-University Education      219
Name: Qualification, dtype: int64

In [10]:
# Check for missing values again
print("Missing values in train data","\n",train.isnull().sum())
print("Missing values in test data","\n", test.isnull().sum())

Missing values in train data
 EmployeeNo                             0
Division                               0
Qualification                          0
Gender                                 0
Channel_of_Recruitment                 0
Trainings_Attended                     0
Year_of_birth                          0
Last_performance_score                 0
Year_of_recruitment                    0
Targets_met                            0
Previous_Award                         0
Training_score_average                 0
State_Of_Origin                        0
Foreign_schooled                       0
Marital_Status                         0
Past_Disciplinary_Action               0
Previous_IntraDepartmental_Movement    0
No_of_previous_employers               0
Promoted_or_Not                        0
dtype: int64
Missing values in test data
 EmployeeNo                             0
Division                               0
Qualification                          0
Gender                                 0
Channel_of_Recruitment                 0
Trainings_Attended                     0
Year_of_birth                          0
Last_performance_score                 0
Year_of_recruitment                    0
Targets_met                            0
Previous_Award                         0
Training_score_average                 0
State_Of_Origin                        0
Foreign_schooled                       0
Marital_Status                         0
Past_Disciplinary_Action               0
Previous_IntraDepartmental_Movement    0
No_of_previous_employers               0
dtype: int64

In [11]:
# Drop duplicates if there is
train = train.drop_duplicates()

### Data Preprocessing

##### One Hot Encode all Categorical variables

In [12]:
# # This one hot encoding is done outside the function because of the need to add a prefix
# train = pd.concat([train, pd.get_dummies(train.No_of_previous_employers, prefix="No_of_previous_employers")], axis=1)
# test = pd.concat([test, pd.get_dummies(test.No_of_previous_employers, prefix="No_of_previous_employers")], axis=1)
# train.drop(['No_of_previous_employers'], axis=1, inplace=True)
# test.drop(['No_of_previous_employers'], axis=1, inplace=True)

In [13]:
# Convert all Categorical Data into Numerical Data
def convert_feature(data):
    if data.dtype == object:
        dummy_df = pd.get_dummies(data, prefix=data.name)
        new_train = pd.concat([train, dummy_df], axis=1)
        new_train.drop([data.name], axis=1, inplace=True)
    else:
        pass
    return new_train

In [14]:
train.columns

Index(['EmployeeNo', 'Division', 'Qualification', 'Gender',
       'Channel_of_Recruitment', 'Trainings_Attended', 'Year_of_birth',
       'Last_performance_score', 'Year_of_recruitment', 'Targets_met',
       'Previous_Award', 'Training_score_average', 'State_Of_Origin',
       'Foreign_schooled', 'Marital_Status', 'Past_Disciplinary_Action',
       'Previous_IntraDepartmental_Movement', 'No_of_previous_employers',
       'Promoted_or_Not'],
      dtype='object')

In [15]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38312 entries, 0 to 38311
Data columns (total 19 columns):
EmployeeNo                             38312 non-null object
Division                               38312 non-null object
Qualification                          38312 non-null object
Gender                                 38312 non-null object
Channel_of_Recruitment                 38312 non-null object
Trainings_Attended                     38312 non-null int64
Year_of_birth                          38312 non-null int64
Last_performance_score                 38312 non-null float64
Year_of_recruitment                    38312 non-null int64
Targets_met                            38312 non-null int64
Previous_Award                         38312 non-null int64
Training_score_average                 38312 non-null int64
State_Of_Origin                        38312 non-null object
Foreign_schooled                       38312 non-null object
Marital_Status                         38312 non-null object
Past_Disciplinary_Action               38312 non-null object
Previous_IntraDepartmental_Movement    38312 non-null object
No_of_previous_employers               38312 non-null object
Promoted_or_Not                        38312 non-null int64
dtypes: float64(1), int64(7), object(11)
memory usage: 5.8+ MB

In [16]:
# Start the Encoding
train = convert_feature(train.Division)
train = convert_feature(train.Qualification)
train = convert_feature(train.Gender)
train = convert_feature(train.Channel_of_Recruitment)
train = convert_feature(train.State_Of_Origin)
train = convert_feature(train.Foreign_schooled)
train = convert_feature(train.Marital_Status)
train = convert_feature(train.Past_Disciplinary_Action)
train = convert_feature(train.Previous_IntraDepartmental_Movement)
train = convert_feature(train.No_of_previous_employers)
train['promoted_or_not'] = train.Promoted_or_Not
train.drop(['Promoted_or_Not'], axis=1, inplace=True)

In [17]:
display(train.head())

,EmployeeNo,Trainings_Attended,Year_of_birth,Last_performance_score,Year_of_recruitment,Targets_met,Previous_Award,Training_score_average,Division_Business Finance Operations,Division_Commercial Sales and Marketing,...,Previous_IntraDepartmental_Movement_No,Previous_IntraDepartmental_Movement_Yes,No_of_previous_employers_0,No_of_previous_employers_1,No_of_previous_employers_2,No_of_previous_employers_3,No_of_previous_employers_4,No_of_previous_employers_5,No_of_previous_employers_More than 5,promoted_or_not
0,YAK/S/00001,2,1986,12.5,2011,1,0,41,0,1,...,1,0,1,0,0,0,0,0,0,0
1,YAK/S/00002,2,1991,12.5,2015,0,0,52,0,0,...,1,0,1,0,0,0,0,0,0,0
2,YAK/S/00003,2,1987,7.5,2012,0,0,42,0,1,...,1,0,1,0,0,0,0,0,0,0
3,YAK/S/00004,3,1982,2.5,2009,0,0,42,0,1,...,1,0,0,1,0,0,0,0,0,0
4,YAK/S/00006,3,1990,7.5,2012,0,0,77,0,0,...,1,0,0,1,0,0,0,0,0,0

In [18]:
# Start Encoding Test data
def convert_test_feature(data):
    if data.dtype == object:
        dummy_df = pd.get_dummies(data, prefix=data.name)
        new_test = pd.concat([test, dummy_df], axis=1)
        new_test.drop([data.name], axis=1, inplace=True)
    else:
        pass
    return new_test



test = convert_test_feature(test.Division)
test = convert_test_feature(test.Qualification)
test = convert_test_feature(test.Gender)
test = convert_test_feature(test.Channel_of_Recruitment)
test = convert_test_feature(test.State_Of_Origin)
test = convert_test_feature(test.Foreign_schooled)
test = convert_test_feature(test.Marital_Status)
test = convert_test_feature(test.Past_Disciplinary_Action)
test = convert_test_feature(test.Previous_IntraDepartmental_Movement)
test = convert_test_feature(test.No_of_previous_employers)

### Start Modeling
Train with all features first to check the accuracy

In [19]:
# Create the feature and the target
X = train.iloc[:, 1:-1]
y = train.promoted_or_not

In [20]:
print(X.shape)
print(y.shape)

(38312, 77)
(38312,)

##### We will be using cross val score to check performance instead of train test split

In [21]:
# Import all models required to train and instantiate all
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

logreg_model = LogisticRegression(solver='liblinear')
decision_model = DecisionTreeClassifier()
knn_model = KNeighborsClassifier(n_neighbors=11)
random_model = RandomForestClassifier(criterion='entropy', n_estimators=100)

In [22]:
from sklearn.model_selection import cross_val_score

models = [logreg_model, decision_model, knn_model, random_model ]
for model in models:
    scores = cross_val_score(model, X, y, cv=10, scoring='accuracy')
    print("Accuracy for ", model,  " is ", scores.mean())

Accuracy for  LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)  is  0.9302304997683567
Accuracy for  DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')  is  0.9000314555288353
Accuracy for  KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=2,
                     weights='uniform')  is  0.9238619230993699
Accuracy for  RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)  is  0.9345374283678476

In [23]:
random_model.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [24]:
test = test.iloc[:, 1:]
prediction = random_model.predict(test)

#### Feature selection

In [26]:
# Drop the years
drop_columns = ['Year_of_birth', 'Year_of_recruitment']
X.drop(drop_columns, axis=1, inplace=True)
test.drop(drop_columns, axis=1, inplace=True)

In [27]:
random_model.fit(X, y)
prediction = random_model.predict(test)

In [28]:
sample.Promoted_or_Not = prediction
sample.to_csv("intercampus3.csv", index=False)

In [29]:
# Preprocess
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
X_scaled = scaler.fit_transform(X)

In [31]:
test_scaled = scaler.fit_transform(test)

In [30]:
scores = cross_val_score(random_model, X_scaled, y, cv=10, scoring='accuracy')
print("Accuracy for ", model,  " is ", scores.mean())

Accuracy for  RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)  is  0.9332063330827923

In [32]:
random_model.fit(X_scaled, y)
prediction = random_model.predict(test_scaled)
sample.Promoted_or_Not = prediction
sample.to_csv("intercampus4.csv", index=False)

In [34]:
from scipy.stats import pearsonr
new_X_columns = []
for i in X.columns:
    corr, _ = pearsonr(X[i], y)
    if corr > 0.15:
        new_X_columns.append(i)

X = X[new_X_columns]
test = test[new_X_columns]
X_scaled = scaler.fit_transform(X)
test_scaled = scaler.fit_transform(test)
random_model.fit(X_scaled, y)
prediction = random_model.predict(test_scaled)
sample.Promoted_or_Not = prediction
sample.to_csv("intercampus5.csv", index=False)